services:
  app:
    image: vladk1m0/docker-owa:latest
    container_name: open-web-analytics
    depends_on:
      - db
    networks:
      - owa_net
    environment:
      - TIME_ZONE="Europe/Warsaw" # Default value UTC
    ports:
      - 8081:80
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  db:
    image: mysql
    volumes:
      - ${DATA1T_DIR:?}/owa_data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=owadb
      - MYSQL_USER=owauser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - owa_net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
networks:
  owa_net:
    driver: bridge
