services:
  openwebrx:
    image: jketterl/openwebrx:latest
    volumes:
      - ${DATA1T_DIR:?}/openwebrx_data/settings:/var/lib/openwebrx
      - ${DATA1T_DIR:?}/openwebrx_data/config:/etc/openwebrx
    ports:
      - 8073:8073
    devices:
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
