services:

    php:
        container_name: lemp_php
        build:
            dockerfile: php-dockerfile
            context: .
        volumes:
            - ${DATA1T_DIR:?}/lemp_data/html:/usr/share/nginx/html
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 13524:80
        links:
            - php
        volumes:
            - ${DATA1T_DIR:?}/lemp_data/html:/usr/share/nginx/html
            - ${DATA1T_DIR:?}/lemp_data/config/nginx.conf:/etc/nginx/nginx.conf
            - ${DATA1T_DIR:?}/lemp_data/config/conf.d:/etc/nginx/conf.d
        depends_on:
            - php

    mariadb:
        image: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DATA1T_DIR:?}/lemp_data/mariadb_data:/var/lib/mysql

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8010:8080
