services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: host
    volumes:
      - "${DATA1T_DIR:?}/samba_data:/data"
      - "${DANE4T_DIR:?}/data4t:/Dane4T"
      - "${FILMY4T_DIR:?}/dlna:/Filmy4T"
      - "${DATA1T_DIR:?}/backup_data:/Data1TBackup"
      - "${DATA1T_DIR:?}/dlna/movies:/Data1TFilmy"
    environment:
      - "TZ=Europe/Warsaw"
      - "SAMBA_LOG_LEVEL=0"
    restart: unless-stopped
