name: immich-folder-album-creator

services:
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: "no"
    user: 1001:1001
    volumes:
     - ./immich_api_key.secret:/immich_api_key.secret:ro
     - ${DANE4T_DIR:?}/data4t/immich_zdjecia:/external_libs/photos
    environment:
      API_URL: ${IMMICH_API_URL}
      API_KEY_FILE: /immich_api_key.secret
      ROOT_PATH: /mnt/photos
      ALBUM_LEVELS: "-2"
      UNATTENDED: "1"
      SYNC_MODE: "2"
     # CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Warsaw
