services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${DATA1T_DIR:?}/homeassistant_data/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
      - /run/dbus:/run/dbus:ro
    devices:
      - ${ZIGBEE_DEVICE}:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host
    mem_limit: 1200m
